"""add indexes to filter columns

Revision ID: f1690cacba77
Revises: 632ea213e0d3
Create Date: 2026-04-02 02:51:43.265293

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1690cacba77"
down_revision: str | Sequence[str] | None = "632ea213e0d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_faqs_intent_label"), "faqs", ["intent_label"], unique=False
    )
    op.create_index(
        op.f("ix_products_department"), "products", ["department"], unique=False
    )
    op.create_index(
        op.f("ix_query_logs_created_at"), "query_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_query_logs_input_hash"), "query_logs", ["input_hash"], unique=False
    )
    op.create_index(
        op.f("ix_query_logs_operation"), "query_logs", ["operation"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_query_logs_operation"), table_name="query_logs")
    op.drop_index(op.f("ix_query_logs_input_hash"), table_name="query_logs")
    op.drop_index(op.f("ix_query_logs_created_at"), table_name="query_logs")
    op.drop_index(op.f("ix_products_department"), table_name="products")
    op.drop_index(op.f("ix_faqs_intent_label"), table_name="faqs")
    # ### end Alembic commands ###
